apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryuzd2793.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
          name: user-java
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SQL_USER
          value: sqladminuZd2793
        - name: SQL_PASSWORD
          value: vH8ig6Em6
        - name: SQL_SERVER
          value: sqlserveruzd2793.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB