apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
  namespace: web
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: tripviewer
              servicePort: 80
            path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress
  namespace: api
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: trips
              servicePort: 80
            path: /api/trips
          - backend:
              serviceName: userprofile
              servicePort: 80
            path: /api/user
          - backend:
              serviceName: user-java
              servicePort: 80
            path: /api/user-java
          - backend:
              serviceName: poi
              servicePort: 80
            path: /api/poi