apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryuzd2793.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
          name: poi
        env:
        - name: SQL_USER
          value: sqladminuZd2793
        - name: SQL_PASSWORD
          value: vH8ig6Em6
        - name: SQL_SERVER
          value: sqlserveruzd2793.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB