apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryuzd2793.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
          name: trips
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SQL_USER
          value: sqladminuZd2793
        - name: SQL_SERVER
          value: sqlserveruzd2793.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        volumeMounts:
          - name: sql-secret
            mountPath: /kvmnt
            readOnly: true
      volumes:
        - name: sql-secret
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: kvcreds
            options:
              usepodidentity: "false"
              keyvaultname: team5kv
              keyvaultobjectnames: sql-password # Name of Key Vault secret
              keyvaultobjecttypes: secret
              resourcegroup: team5
              subscriptionid: 2797869a-f18f-4acc-95ac-3e2c15960d62
              tenantid: e0e3ea7e-63e7-4367-94f5-d77adf8abbb0